---
- name: Check for missing updates
  ansible.windows.win_updates:
    category_names: "{{ win_update_category_names }}"
    state: searched
  register: available_updates
  
- name: save file
  template:
    src: update_report.html.j2
    dest: update_report.html
  delegate_to: localhost
  become: true
  when: save_report_locally | bool