---
- name: This sets up an httpd webserver
  hosts: all_linux_targets
  tasks:
    - name: Install the latest version of Apache
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        state: started
        enabled: true
        name: httpd