---
- name: Ensure IIS is installed and started
  hosts: demo_windows_targets
  become: true
  gather_facts: false
  vars:
    service_name: IIS Admin Service

  tasks:
  - name: Ensure IIS Server is present
    win_feature:
      name: Web-Server
      state: present

  - name: Ensure latest index.html file is present
    win_copy:
      src: files/index.html
      dest: c:\www\

  - name: Ensure IIS is started
    win_service:
      name: "{{ service_name }}"
      state: started
