---
- name: Reboot Windows targets
  hosts: demo_windows_targets
  become: true
  gather_facts: false
  tasks:
    # - name: Install Windows ADK with DISM for Server 2008 R2
    #   chocolatey.chocolatey.win_chocolatey:
    #     name: windows-adk
    #     version: 8.100.26866.0
    #     state: present
    #     install_args: /features OptionId.DeploymentTools

    - name: Install hotfix without validating the KB and Identifier
      community.windows.win_hotfix:
        source: C:\temp\windows8.1-kb3172729-x64_e8003822a7ef4705cbb65623b72fd3cec73fe222.msu
        state: present
      register: hotfix_install
      tags: nonvalidated_hotfix

    - name: Reboot post hotfix applied with nonvalidated_hotfix tags
      ansible.windows.win_reboot:
        reboot_timeout: 360
      when: hotfix_install.reboot_required

    - name: Install hotfix validating KB
      community.windows.win_hotfix:
        hotfix_kb: KB3172729
        source: C:\temp\windows8.1-kb3172729-x64_e8003822a7ef4705cbb65623b72fd3cec73fe222.msu
        state: present
      register: hotfix_install
      tags: validated_hotfix

    - name: Reboot post hotfix applied with validated_hotfix tags
      ansible.windows.win_reboot:
        reboot_timeout: 360
      when: hotfix_install.reboot_required

    # - name: Install hotfix validating Identifier
    #   community.windows.win_hotfix:
    #     hotfix_identifier: Package_for_KB3172729~31bf3856ad364e35~amd64~~6.3.1.0
    #     source: C:\temp\windows8.1-kb3172729-x64_e8003822a7ef4705cbb65623b72fd3cec73fe222.msu
    #     state: present
    #   register: hotfix_install

    # - ansible.windows.win_reboot:
    #   when: hotfix_install.reboot_required

    # - name: Uninstall hotfix with Identifier
    #   community.windows.win_hotfix:
    #     hotfix_identifier: Package_for_KB3172729~31bf3856ad364e35~amd64~~6.3.1.0
    #     state: absent
    #   register: hotfix_uninstall

    # - ansible.windows.win_reboot:
    #   when: hotfix_uninstall.reboot_required

    # - name: Uninstall hotfix with KB (not recommended)
    #   community.windows.win_hotfix:
    #     hotfix_kb: KB3172729
    #     state: absent
    #   register: hotfix_uninstall

    # - ansible.windows.win_reboot:
    #   when: hotfix_uninstall.reboot_required
